# Site settings
email: ronapelbaum@gmail.com
baseurl: /teaamim-2017
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: טעמים 2017
description: 
url: https://ronapelbaum.github.io
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:title/
categoriesMap:
  fish: דגים
  side-dish: תוספות ומרקים
  main-dish: עיקריות
  _lesson-01: שיעור 1
  _lesson-02: שיעור 2
  _lesson-03: שיעור 3
  _lesson-04: שיעור 4
  _lesson-05: שיעור 5
  _lesson-06: שיעור 6
  _lesson-07: שיעור 7
  _lesson-08: שיעור 8
  _lesson-09: שיעור 9
  _lesson-10: שיעור 10
  _lesson-11: שיעור 11
  _lesson-12: שיעור 12
  _lesson-13: שיעור 13

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
