# Site settings
email: 
baseurl: /cooking
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: אוכל טעים
description: 
url: https://ronapelbaum.github.io
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
